/**
 * Codegen: `src/shared/compiler/styles/*.css` → the committed
 * `src/shared/compiler/styles/styles.generated.ts` (one named export per fragment).
 *
 * The fragments are authored as real CSS (comments, one rule per line); `normalize()` strips
 * the comments and joins the rules into the compact single-line form `stylesheet()` inlines
 * into `<style>` — intra-line bytes pass through VERBATIM (the significant spaces inside
 * `calc()` / `color-mix()` must survive, so this is deliberately not a minifier).
 *
 * The generator is file-set-agnostic: it scans the directory, so adding/removing a fragment
 * needs no edit here. Consumers: css.ts (runtime), esbuild.config.js (regenerates on every
 * build; watch mode re-runs it when a fragment changes), and styles-codegen.test.ts (fails
 * with a pointer to `npm run gen:styles` when the committed module is stale).
 */
import { readdir, readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const STYLES_DIR = fileURLToPath(new URL('../src/shared/compiler/styles/', import.meta.url));
const GENERATED = join(STYLES_DIR, 'styles.generated.ts');

const HEADER = `// GENERATED by scripts/gen-styles.ts from the sibling *.css fragments — DO NOT EDIT.
// Run \`npm run gen:styles\` after editing a fragment (a normal build regenerates it too).
`;

/** `preview.base.css` → `previewBase` (dots/dashes camel-cased away). */
function exportName(file: string): string {
  return file
    .replace(/\.css$/, '')
    .replace(/[.-]([a-z0-9])/gi, (_m, c: string) => c.toUpperCase());
}

/** Strip block comments + blank lines + per-line indentation; intra-line bytes verbatim. */
function normalize(css: string): string {
  return css
    .replace(/\/\*[\s\S]*?\*\//g, '')
    .split('\n')
    .map((line) => line.trim())
    .filter((line) => line !== '')
    .join('');
}

/** The absolute paths of the fragment sources (esbuild watch re-triggers on these). */
export async function styleSourcePaths(): Promise<string[]> {
  const files = await readdir(STYLES_DIR);
  return files.filter((f) => f.endsWith('.css'))
    .sort()
    .map((f) => join(STYLES_DIR, f));
}

/** Renders the full generated-module text (pure; the drift test compares against this). */
export async function generateStylesModule(): Promise<string> {
  const paths = await styleSourcePaths();
  const styles = await Promise.all(paths.map(async (path) => [path, normalize(await readFile(path, 'utf8'))] as const));
  const exports = styles.map(([path, css]) => {
    const file = path.slice(path.lastIndexOf('/') + 1);
    return `export const ${exportName(file)} = ${JSON.stringify(css)};\n`;
  });
  return HEADER + exports.join('');
}

/** Write the module iff its content changed; returns whether a write happened. */
export async function writeStylesModule(): Promise<boolean> {
  const next = await generateStylesModule();
  let prev: string | undefined;
  try {
    prev = await readFile(GENERATED, 'utf8');
  } catch {
    prev = undefined; // first generation
  }
  if (prev === next) {
    return false;
  }
  await writeFile(GENERATED, next);
  return true;
}

// CLI: `node scripts/gen-styles.ts` (or via `npm run gen:styles`).
if (process.argv[1] !== undefined && import.meta.url === pathToFileURL(process.argv[1]).href) {
  writeStylesModule().then((changed) => {
    console.log(changed ? `regenerated ${GENERATED}` : `up to date: ${GENERATED}`);
  }).catch((err: unknown) => {
    console.error(`error generating ${GENERATED}:`, err);
    process.exit(1);
  });
}
