/**
 * Codegen: the notation (`src/shared/ast/notation.ts`) and the colour of each part role
 * (`src/server/semanticTokens.ts`) → `syntaxes/jpnov.tmLanguage.json`, the TextMate grammar that
 * colours a .jpnov before the language server is up. Gitignored, regenerated by `npm run gen`
 * (also `prepare`) and every esbuild build; test/server/highlight/grammar.test.ts checks it
 * against the semantic tokens.
 */
import { fileURLToPath } from 'node:url';

import type { PartRole } from '../src/shared/ast/nodes.ts';
import {
  ANNOTATION_CLOSE,
  ANNOTATION_OPEN,
  BASE_MARK,
  BLOCK_FROM,
  BLOCK_TO,
  CONNECTOR_HA,
  CONNECTOR_NI,
  CORNER_CLOSE,
  CORNER_OPEN,
  EMPHASIS_VARIANTS,
  GAIJI,
  GAIJI_MARK,
  HEADING_LITERALS,
  INDENT,
  INDENT_MAX,
  LEFT_LONG,
  LEFT_RUBY,
  LEFT_SHORT,
  PAGE_BREAK,
  RUBY_CLOSE,
  RUBY_OPEN,
  SPAN_END,
  TCY,
  VALUE_HERE,
  VALUE_SHOW,
  hasBlockForm,
  hasLeftSide,
} from '../src/shared/ast/notation.ts';
import { CORNERS } from '../src/server/dialogue.ts';
import { partHighlight } from '../src/server/semanticTokens.ts';

import { runCli, writeIfChanged } from './write.ts';

const GENERATED = fileURLToPath(new URL('../syntaxes/jpnov.tmLanguage.json', import.meta.url));

const HEADER = [
  'GENERATED by scripts/gen-grammar.ts from src/shared/ast/notation.ts and the part colours of',
  'src/server/semanticTokens.ts — DO NOT EDIT; run `npm run gen:grammar` (a build regenerates it too).',
  'Every pattern is a single-line match, as the scanner bounds an annotation to its line: an unclosed ［＃',
  'is greyed to the line end, a lone 《 or a stray ］ stays default text. The scope of a part is the LSP',
  'token type and the highlight of its role, so the semantic tokens refine the colours invisibly when the server is up.',
].join(' ');

/** One part of a rule: its role and the regex of what it spells, without a group of its own. */
interface Segment {
  readonly role: PartRole;
  readonly re: string;
  readonly optional?: true;
}

interface Rule {
  readonly comment: string;
  readonly parts: readonly Segment[];
  /** An anchor before the parts: `^` for the line-head 字下げ. */
  readonly head?: string;
}

interface Pattern {
  readonly comment: string;
  readonly match: string;
  readonly captures: Record<string, { readonly name: string }>;
}

const esc = (s: string): string => s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');

/** `vs` as a regex alternation, the longest first so that no spelling hides a longer one. */
const alt = (vs: readonly string[]): string => [...vs].sort((a, b) => b.length - a.length).map(esc).join('|');

const lit = (role: PartRole, text: string): Segment => ({ role, re: esc(text) });
const kw = (re: string): Segment => ({ role: 'keyword', re });
/** Anything but the characters of `stop`, non-empty. */
const upTo = (role: PartRole, stop: string): Segment => ({ role, re: `[^${esc(stop)}]+` });

const OPEN = lit('bracket', ANNOTATION_OPEN);
const CLOSE = lit('bracket', ANNOTATION_CLOSE);
const END = lit('scaffold', SPAN_END);
const INNER: Segment = { role: 'inner', re: `[^${esc(ANNOTATION_CLOSE)}]*` };
/** The left side of a span, 左に. */
const LEFT: Segment = { ...lit('direction', LEFT_SHORT), optional: true };
/** 「対象」: the target keeps the default colour; it never holds a 」. */
const TARGET: readonly Segment[] = [lit('corner', CORNER_OPEN), upTo('target', CORNER_CLOSE), lit('corner', CORNER_CLOSE)];

const VARIANTS = Object.keys(EMPHASIS_VARIANTS);
/** 傍点／傍線: the variants with a left side. */
const DOT_LINE = alt(VARIANTS.filter(hasLeftSide));
/** 太字／斜体／縦中横／見出し: the command words without one; a postfix of theirs takes は. */
const PLAIN = alt([...VARIANTS.filter((v) => !hasLeftSide(v)), TCY, ...HEADING_LITERALS]);
const BLOCK = alt([...VARIANTS.filter(hasBlockForm), ...HEADING_LITERALS]);

// A digit count can spell the maximum only while it is all nines (indentAmount reads any leading zeros).
const WIDTH = String(INDENT_MAX).length;
if (INDENT_MAX !== 10 ** WIDTH - 1) {
  throw new Error(`INDENT_MAX ${String(INDENT_MAX)} is not all nines`);
}
const INDENT_COUNT = `０*[０-９]{1,${String(WIDTH)}}${esc(INDENT)}`;

/** The annotation forms the scanner reads, in order: a form whose spelling ends another's precedes it. */
const ANNOTATION: readonly Rule[] = [
  { comment: '改ページ.', parts: [OPEN, lit('keyword', PAGE_BREAK), CLOSE] },
  {
    comment: '値の表示 ［＃ここに「名前」の値を表示］: any non-empty name; an unknown one shows as itself.',
    parts: [OPEN, lit('scaffold', VALUE_HERE), lit('corner', CORNER_OPEN), upTo('name', ANNOTATION_CLOSE), lit('corner', CORNER_CLOSE), lit('scaffold', VALUE_SHOW), CLOSE],
  },
  {
    comment: 'Block END ［＃ここで…終わり］, before the block START its 終わり would hide. 傍点／傍線 have no block form.',
    parts: [OPEN, lit('scaffold', BLOCK_TO), kw(`${esc(INDENT)}|${BLOCK}`), END, CLOSE],
  },
  {
    comment: 'Block START ［＃ここから…］: a 字下げ count in full-width digits up to the maximum; the 折り返して form is a comment.',
    parts: [OPEN, lit('scaffold', BLOCK_FROM), kw(`${INDENT_COUNT}|${BLOCK}`), CLOSE],
  },
  { comment: 'Single-line ［＃○字下げ］ at the line head only; elsewhere it is a comment.', head: '^', parts: [OPEN, kw(INDENT_COUNT), CLOSE] },
  { comment: '傍点／傍線 span END, before its START; the span form spells its left side 左に.', parts: [OPEN, LEFT, kw(DOT_LINE), END, CLOSE] },
  { comment: '傍点／傍線 span START.', parts: [OPEN, LEFT, kw(DOT_LINE), CLOSE] },
  { comment: '太字／斜体／縦中横／見出し span END, before its START.', parts: [OPEN, kw(PLAIN), END, CLOSE] },
  { comment: '太字／斜体／縦中横／見出し span START.', parts: [OPEN, kw(PLAIN), CLOSE] },
  { comment: '傍点／傍線 postfix ［＃「対象」に…］: the connector に, or none.', parts: [OPEN, ...TARGET, { ...lit('connector', CONNECTOR_NI), optional: true }, kw(DOT_LINE), CLOSE] },
  { comment: '傍点／傍線 postfix on the left side ［＃「対象」の左に…］: の左に in the connector\'s place.', parts: [OPEN, ...TARGET, lit('direction', LEFT_LONG), kw(DOT_LINE), CLOSE] },
  { comment: '太字／斜体／縦中横／見出し postfix ［＃「対象」は…］: the connector は is required.', parts: [OPEN, ...TARGET, lit('connector', CONNECTOR_HA), kw(PLAIN), CLOSE] },
  {
    comment: '左ルビ ［＃「対象」の左に「よみ」のルビ］: the reading is non-empty and holds no corner.',
    parts: [OPEN, ...TARGET, lit('direction', LEFT_LONG), lit('corner', CORNER_OPEN), upTo('reading', CORNER_OPEN + CORNER_CLOSE), lit('corner', CORNER_CLOSE), lit('keyword', LEFT_RUBY), CLOSE],
  },
  {
    comment: '外字注記 ※［＃…］, the ones the scanner reads: it starts a character before the comment rule, so it wins wherever it sits.',
    parts: [lit('bracket', GAIJI_MARK + ANNOTATION_OPEN), kw(alt(Object.keys(GAIJI))), CLOSE],
  },
  { comment: 'Any other closed ［＃…］ is a comment.', parts: [OPEN, INNER, CLOSE] },
  { comment: 'An unclosed ［＃ up to the line end; last, so every closed form wins first.', parts: [OPEN, INNER] },
];

const RUBY: readonly Rule[] = [
  { comment: 'A 《reading》 with its brackets; the base before it keeps the default colour.', parts: [lit('bracket', RUBY_OPEN), upTo('reading', RUBY_CLOSE), lit('bracket', RUBY_CLOSE)] },
  { comment: 'The ｜ of an explicit base.', parts: [lit('bracket', BASE_MARK)] },
];

const DIALOGUE: readonly Rule[] = [
  { comment: 'The dialogue corners, one by one: the grammar keeps no state across lines.', parts: [{ role: 'corner', re: CORNERS.source }] },
];

function pattern(rule: Rule): Pattern {
  let match = rule.head ?? '';
  const captures: Record<string, { name: string }> = {};
  rule.parts.forEach((part, i) => {
    match += `(${part.re})${part.optional === true ? '?' : ''}`;
    const highlight = partHighlight(part.role);
    if (highlight !== null) {
      captures[String(i + 1)] = { name: `${highlight.lsp}.${highlight.kind}.jpnov` };
    }
  });
  return { comment: rule.comment, match, captures };
}

/** The grammar as an object (pure). */
export function generateGrammar() {
  const repository = { annotation: ANNOTATION, ruby: RUBY, dialogue: DIALOGUE };
  return {
    name: 'Japanese Novel',
    scopeName: 'text.jpnov',
    comment: HEADER,
    patterns: Object.keys(repository).map((name) => ({ include: `#${name}` })),
    repository: Object.fromEntries(Object.entries(repository).map(([name, rules]) => [name, { patterns: rules.map(pattern) }])),
  };
}

/** Write the grammar iff its content changed; returns whether a write happened. */
export async function writeGrammar(): Promise<boolean> {
  return writeIfChanged(GENERATED, `${JSON.stringify(generateGrammar(), null, 2)}\n`);
}

// CLI: `node scripts/gen-grammar.ts` (or via `npm run gen:grammar`).
runCli(import.meta.url, GENERATED, writeGrammar);
